# -*- coding: utf-8 -*-
"""AttendanceData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPbAXJLQylfwHjClWb_k9kfEGnpfflEf
"""

import pandas as pd

attendance_data = pd.read_csv('/content/Attendance_Data.csv')

attendance_data_info = attendance_data[[
    "Student ID", "Attendance Date", "Attendance Code", "Class Section ID", "Excused",
    "Faculty ID", "Subject ID"
    ]]

attendance_data_info.loc[:, 'Excused'] = attendance_data_info['Excused'].apply(lambda x: 'Yes' if x == 'Yes' else 'No')

attendance_data_absences_lates = attendance_data_info.groupby('Student ID').agg(
    unexcused_absences=pd.NamedAgg(column='Attendance Code',
                                   aggfunc=lambda x: sum((x == 'Absent') & (attendance_data_info['Excused'] == 'No'))),
    unexcused_lates = pd.NamedAgg(column='Attendance Code',
                                  aggfunc=lambda x: sum((x == 'Late') & (attendance_data_info['Excused'] == 'No')))
).reset_index()

print(attendance_data_absences_lates.head())

conduct_grades = pd.read_csv("Grades.csv").rename(columns={"Name": "Student ID"})

grades_joined_absences = conduct_grades.merge(attendance_data_absences_lates, on='Student ID', how='left').fillna(0)

print(grades_joined_absences.head())

grades_joined_absences['final_conduct_grade'] = grades_joined_absences['Conduct Grade'] - \
                                                grades_joined_absences['unexcused_absences'] - \
                                                grades_joined_absences['unexcused_lates']

final_grade = grades_joined_absences[['Student ID', 'final_conduct_grade']]

print(final_grade)